PLANILHAS = ["NCM E CEST", "Estoque", "notas"]

NOTAS_COLS = [
    ("empresa_codigo",                     "Empresa"),
    ("codigo_da_loja",                     "Cód. Loja"),
    ("codigo_do_fornecedor",               "Cód. Fornecedor"),
    ("nome_do_fornecedor",                 "Nome Fornecedor"),
    ("numero_do_documento",                "Nº Documento"),
    ("codigo_da_operacao",                 "Cód. Operação"),
    ("operacao",                           "Operação"),
    ("situacao",                           "Situação"),
    ("data_de_emissao",                    "Data Emissão"),
    ("data_de_entrada",                    "Data Entrada"),
    ("frete",                              "Frete"),
    ("outros",                             "Outros"),
    ("seguro",                             "Seguro"),
    ("desconto",                           "Desconto"),
    ("ipi",                                "IPI"),
    ("dae",                                "DAE"),
    ("icms_desonerado",                    "ICMS Desonerado"),
    ("fecop",                              "FECOP"),
    ("valor_fecopst",                      "Valor FECOPST"),
    ("fecop_retido",                       "FECOP Retido"),
    ("base_de_calculo_icms",               "BC ICMS"),
    ("valor_bc_do_icms",                   "Valor BC ICMS"),
    ("base_de_calculo_icmsst",             "BC ICMSST"),
    ("valor_bc_icmsst",                    "Valor BC ICMSST"),
    ("valor_total",                        "Valor Total"),
    ("codigo_do_produto",                  "Cód. Produto"),
    ("descricao_produto",                  "Descrição Produto"),
    ("unidade_de_medida",                  "Unidade"),
    ("quantidade_de_itens_na_unidade",     "Qtd Un."),
    ("quantidade_de_itens",                "Qtd Itens"),
    ("cfop",                               "CFOP"),
    ("frete_do_item",                      "Frete Item"),
    ("seguro_do_item",                     "Seguro Item"),
    ("desconto_do_item",                   "Desconto Item"),
    ("ipi_do_item",                        "IPI Item"),
    ("base_de_calculo_do_icms_do_item",    "BC ICMS Item"),
    ("icms_do_item",                       "ICMS Item"),
    ("base_de_calculo_do_icms_st_do_item", "BC ICMSST Item"),
    ("icms_st_do_item",                    "ICMSST Item"),
    ("dae_item",                           "DAE Item"),
    ("icms_desonerado_do_item",            "ICMS Desonerado Item"),
    ("icms_antecipado_do_item",            "ICMS Antecipado Item"),
    ("fecop_do_item",                      "FECOP Item"),
    ("fecop_st_do_item",                   "FECOP ST Item"),
    ("fecop_retido_do_item",               "FECOP Retido Item"),
    ("valor_unitario",                     "Valor Unitário"),
    ("outras_despesas_do_item",            "Outras Despesas"),
    ("valor_total_do_item",                "Valor Total Item"),
    ("posicao_na_nf",                      "Posição NF"),
    ("chave_nfe",                          "Chave NFe"),
]

NOTAS_FILTROS = [
    ("empresa_codigo",      "Empresa"),
    ("codigo_da_loja",      "Cód. Loja"),
    ("nome_do_fornecedor",  "Nome Fornecedor"),
    ("numero_do_documento", "Nº Documento"),
    ("operacao",            "Operação"),
    ("situacao",            "Situação"),
    ("data_de_emissao",     "Data Emissão"),
    ("data_de_entrada",     "Data Entrada"),
    ("cfop",                "CFOP"),
    ("codigo_do_produto",   "Cód. Produto"),
    ("descricao_produto",   "Descrição Produto"),
]
ESTOQUE_FILTROS = [  
    ("empresa_codigo", "Empresa"),  
    ("produto",        "Produto"),  
    ("descricao",      "Descrição"),  
    ("unidade",        "Unidade"),  
    ("saldo_atual",    "Saldo Atual"),  
]  